### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by akainth015** [jz222/personal-website#4]
Hello! I forked this repository because I really like the basic theme that it sets for the website, and I decided to base the next version of my website on it (with some significant modifications). While replacing content, I noticed a couple of errors I thought I'd let you know about.

Both errors are on [this line](https://github.com/jz222/personal-website/blob/master/src/content/labels.js#L48), one is "thinkin", and the other is "maintainbale".

Thank you for making this source available for us to use!

**Comment by jz222** [comment]
Hi,

thanks a lot for pointing it out! I've just fixed them.

You can use the website as foundation for yours, but please make sure to make significant changes, otherwise, the personal website is not so personal anymore. :)

I'm actually working on a website and blog template that is absolutely free for everyone to use, but this site should remain my individual and personal one.

Thank you.
